[phases.setup]
nixPkgs = ["...", "fontconfig", "freetype"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "NODE_OPTIONS='--max-old-space-size=800' npm run build"]
